/*
 * This file is part of BlendInt (a Blender-like Interface Library in
 * OpenGL).
 *
 * BlendInt (a Blender-like Interface Library in OpenGL) is free
 * software: you can redistribute it and/or modify it under the terms
 * of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * BlendInt (a Blender-like Interface Library in OpenGL) is
 * distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with BlendInt.  If not, see
 * <http://www.gnu.org/licenses/>.
 *
 * Contributor(s): Freeman Zhang <zhanggyb@gmail.com>
 */

#ifndef _BLENDINT_GLBUFFER_HPP_
#define _BLENDINT_GLBUFFER_HPP_

#include <map>

#define BUFFER_OFFSET(bytes) ((GLubyte*) NULL + (bytes))

namespace BlendInt {

	/**
	 * @brief A simple warpper of OpenGL buffer
	 *
	 * @ingroup opengl
	 */
	class GLBuffer
	{
	public:

		GLBuffer ();

		~GLBuffer ();

		/**
		 * @brief create a buffer with the given key
		 * @param key an integer for identify a gl buffer, it's not the same as a
		 * buffer id return by glGenBuffers(), but a key in the map of buffers
		 *
		 * This function search the key in the built-in map, if the key was not
		 * used, create a new gl buffer. And set the current buffer to the one
		 * defined by key, so the next functions (bind(), upload(), etc.) use this
		 * buffer.
		 */
		void create (int key);

		/**
		 * @brief set buffer found by key to the current buffer for other operations
		 * @param key the unique keyword in buffer map
		 *
		 * This function raises an invalid_argument exception if it's not found in buffer
		 * map
		 *
		 * @ingroup functions_throw_exception
		 */
		void select (int key);

		int vertices ()
		{
			return m_map[m_key].vertices;
		}

		int vertices (int key)
		{
			return m_map[key].vertices;
		}

		void set_vertices (int vertices);

		void set_vertices (int key, int vertices);

		int unit_size ()
		{
			return m_map[m_key].unit_size;
		}

		int unit_size (int key)
		{
			return m_map[key].unit_size;
		}

		void set_unit_size (int size);

		void set_unit_size (int key, int size);

		GLenum target ()
		{
			return m_map[m_key].target;
		}

		GLenum target (int key)
		{
			return m_map[key].target;
		}

		void set_target (GLenum target);

		void set_target (int key, GLenum target);

		GLenum usage ()
		{
			return m_map[m_key].usage;
		}

		GLenum usage (int key)
		{
			return m_map[key].usage;
		}

		void set_usage (GLenum usage);

		void set_usage (int key, GLenum usage);

		void set_property (int vertices, int unit_size, GLenum target, GLenum usage);

		void set_property (int key, int vertices, int unit_size, GLenum target, GLenum usage);

		/**
		 * @brief bind current buffer
		 * @return
		 */
		void bind ();

		void bind (int key);

		/**
		 * @brief unbind the buffer id in current index
		 */
		void unbind ();

		void unbind (int key);

		/**
		 * @brief return the current index in the buffer vector
		 * @return
		 */
		int key () const {return m_key;}

		size_t size () const {return m_map.size();}

		bool is_buffer ();

		bool is_buffer (int key);

		/**
		 * @brief creates and initializes a buffer object's data store
		 * @param target
		 * @param size
		 * @param data
		 * @param usage
		 */
		void upload (const GLvoid* data);

		void upload (int key, const GLvoid* data);

		void destroy ();

		void destroy (int key);

		void clear ();

	private:

		struct Property
		{
			Property ()
			: id(0), vertices(0), unit_size(0), target(0), usage(0)
			{}

			/** The name of a buffer object, it's generated by glGenBuffers() and used in glBindBuffers() */
			GLuint id;

			/** Vertex number -- how many vertices are used in this buffer */
			int vertices;

			/** size of one unit vertex */
			int unit_size;

			/** The target buffer object, it's used for glBindBuffer() and glBufferData() */
			GLenum target;

			/** Usage: */
			GLenum usage;
		};

		int m_key;

		std::map<int, Property> m_map;
	};
}

#endif /* _BIL_GLBUFFER_HPP_ */
